export const instantBuffs: BuffInterface[] = [
  {
    name: "Patience",
    emoji: "🧘",
    type: "instantBuffs",
    price: 29.99,
    description: "Stay calm under pressure",
    tagline: "Zen mode activated",
  },
  {
    name: "Strength",
    emoji: "💪",
    type: "instantBuffs",
    price: 29.99,
    description: "Feel physically and mentally empowered",
    tagline: "Unlock your inner powerhouse",
  },
  {
    name: "Courage",
    emoji: "🦁",
    type: "instantBuffs",
    price: 29.99,
    description: "Face fears with bravery",
    tagline: "Brave heart activated",
  },
  {
    name: "Wisdom",
    emoji: "🦉",
    type: "instantBuffs",
    price: 29.99,
    description: "Make smarter decisions",
    tagline: "Ancient knowledge unlocked",
  },
  {
    name: "Charisma",
    emoji: "😎",
    type: "instantBuffs",
    price: 29.99,
    description: "Shine in social situations",
    tagline: "Magnetic personality engaged",
  },
  {
    name: "Focus",
    emoji: "🎯",
    type: "instantBuffs",
    price: 29.99,
    description: "Concentrate deeply on tasks",
    tagline: "Laser precision mode",
  },
];

export const dailyBlessings: BuffInterface[] = [
  {
    name: "Luck",
    emoji: "🍀",
    type: "dailyBlessings",
    price: 29.99,
    description: "Attract good fortune",
    tagline: "Fortune favors the boosted",
  },
  {
    name: "Motivation",
    emoji: "🏃",
    type: "dailyBlessings",
    price: 29.99,
    description: "Get up and go energy",
    tagline: "Morning momentum delivered",
  },
  {
    name: "Creativity",
    emoji: "🎨",
    type: "dailyBlessings",
    price: 29.99,
    description: "Unlock innovative thinking",
    tagline: "Inspiration on tap",
  },
  {
    name: "Energy",
    emoji: "⚡",
    type: "dailyBlessings",
    price: 29.99,
    description: "Natural vitality boost",
    tagline: "Battery fully charged",
  },
  {
    name: "Clarity",
    emoji: "🔍",
    type: "dailyBlessings",
    price: 29.99,
    description: "Clear mind for clear decisions",
    tagline: "Mental fog cleared",
  },
  {
    name: "Gratitude",
    emoji: "🙏",
    type: "dailyBlessings",
    price: 29.99,
    description: "Appreciate life's blessings",
    tagline: "Thankfulness amplified",
  },
];
